image: node:latest # (1)

stages:
  - build

cache:
  paths:
    - node_modules/ # (2)


install_dependencies:
  stage: build
  script:
    - npm install # (3)
  artifacts:
    paths:
      - node_modules/

